//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppControl_Notas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALIFICACION
    {
        public int ID_CALIFICACION { get; set; }
        public int ID_MATRICULA { get; set; }
        public int ID_ASIGNATURA { get; set; }
        public double CAL_PARCIAL_1 { get; set; }
        public int CAL_ASISTENCIA_1 { get; set; }
        public double CAL_PARCIAL_2 { get; set; }
        public int CAL_ASISTENCIA_2 { get; set; }
        public double CAL_PARCIAL_3 { get; set; }
        public int CAL_ASISTENCIA_3 { get; set; }
        public double CAL_FINAL { get; set; }
        public string CAL_OBSERVACION { get; set; }
        public string CAL_ESTADO { get; set; }
    
        public virtual ASIGNATURA ASIGNATURA { get; set; }
        public virtual MATRICULA MATRICULA { get; set; }
    }
}
