//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppControl_Notas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCENTE()
        {
            this.ASIGNATURA_DOCENTE = new HashSet<ASIGNATURA_DOCENTE>();
        }
    
        public int ID_DOCENTE { get; set; }
        public string DOC_CEDULA { get; set; }
        public string DOC_NOMBRES { get; set; }
        public string DOC_APELLIDO_PATERNO { get; set; }
        public string DOC_APELLIDO_MATERNO { get; set; }
        public System.DateTime DOC_FECHA_NACIMIENTO { get; set; }
        public string DOC_DIRECCION { get; set; }
        public string DOC_TELEFONO_FIJO { get; set; }
        public string DOC_TELEFONO_CELULAR { get; set; }
        public string DOC_CORREO_PERSONAL { get; set; }
        public string DOC_CORREO_INSTITUCIONAL { get; set; }
        public bool DOC_ESTADO { get; set; }
        public System.DateTime DOC_FECHA_INGRESO { get; set; }
        public Nullable<System.DateTime> DOC_FECHA_SALIDA { get; set; }
        public string DOC_TIPO { get; set; }
        public string DOC_USUARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASIGNATURA_DOCENTE> ASIGNATURA_DOCENTE { get; set; }
    }
}
