//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppControl_Notas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTUDIANTE()
        {
            this.MATRICULA = new HashSet<MATRICULA>();
        }
    
        public int ID_ESTUDIANTE { get; set; }
        public string EST_CEDULA { get; set; }
        public string EST_NOMBRE { get; set; }
        public string EST_APELLIDO_PATERNO { get; set; }
        public string EST_APELLIDO_MATERNO { get; set; }
        public System.DateTime EST_FECHA_NACIMIENTO { get; set; }
        public string EST_DIRECCION { get; set; }
        public string EST_TELEFONO_FIJO { get; set; }
        public string EST_TELEFONO_CELULAR { get; set; }
        public string EST_CORREO_PERSONAL { get; set; }
        public string EST_CORREO_INSTITUCIONAL { get; set; }
        public string EST_USUARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATRICULA> MATRICULA { get; set; }
    }
}
