//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppControl_Notas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRICULA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATRICULA()
        {
            this.CALIFICACION = new HashSet<CALIFICACION>();
            this.NIVEL = new HashSet<NIVEL>();
        }
    
        public int ID_MATRICULA { get; set; }
        public int ID_PERIODO { get; set; }
        public int ID_ESTUDIANTE { get; set; }
        public System.DateTime MAT_FECHA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALIFICACION> CALIFICACION { get; set; }
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        public virtual PERIODO PERIODO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NIVEL> NIVEL { get; set; }
    }
}
