//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppControl_Notas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIVEL
    {
        public int ID_NIVEL { get; set; }
        public int ID_MATRICULA { get; set; }
        public string NIV_DESCRIPCION { get; set; }
        public int NIV_SECUENCIAL { get; set; }
        public string NIV_OBSERVACION { get; set; }
    
        public virtual MATRICULA MATRICULA { get; set; }
    }
}
