//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppControl_Notas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string USU_LOGIN { get; set; }
        public string USU_CONTRASENA { get; set; }
        public System.DateTime USU_FECHA_REGISTRO { get; set; }
        public string USU_TIPO { get; set; }
        public Nullable<System.DateTime> USU_CADUCIDAD { get; set; }
    }
}
